onboarding = false
# herdr configuration
[theme]
name = "vesper"
auto_switch = false

[keys]
prefix = "ctrl+s"

focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"
previous_workspace = "prefix+("
next_workspace = "prefix+)"

split_vertical = "prefix+%"
split_horizontal = 'prefix+"'
new_tab = "prefix+c"

[ui.toast]
delivery = "system"

[ui]
pane_gaps = false
agent_panel_sort = "spaces"
