[general]
	live_config_reload = true
[window]
	padding = {x = 15, y = 10}
	decorations = "buttonless"
	startup_mode = "SimpleFullscreen"
    # blur = true
    # opacity = 0.5
[font]
	normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
	size = 15
[selection]
	save_to_clipboard = true
