[general]
	live_config_reload = true
[window]
	padding = {x = 15, y = 10}
	decorations = "buttonless"
	opacity = 0.5
	blur = true
	startup_mode = "SimpleFullscreen"
[font]
	normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
	size = 15
[selection]
	save_to_clipboard = true
